"""initial

Revision ID: 4c695bb4980a
Revises:
Create Date: 2024-09-12 16:28:32.231229

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c695bb4980a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('employee',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('username', sa.String(length=50), nullable=False),
    # sa.Column('first_name', sa.String(length=50), nullable=False),
    # sa.Column('last_name', sa.String(length=50), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('username')
    # )
    # op.create_table('organization',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('description', sa.Text(), nullable=False),
    # sa.Column('type', sa.Enum('IE', 'LLC', 'JSC', name='organization_type'), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('organization_responsible',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('organization_id', sa.UUID(), nullable=False),
    # sa.Column('user_id', sa.UUID(), nullable=False),
    # sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['user_id'], ['employee.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.create_table(
        'tender_history',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tender_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('CREATED', 'PUBLISHED', 'CLOSED', name='tenderstatus'),
            nullable=False,
        ),
        sa.Column(
            'service_type',
            sa.Enum(
                'CONSTRUCTION', 'DELIVERY', 'MANUFACTURE', name='servicetype'
            ),
            nullable=False,
        ),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organization.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['employee.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'tenders',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('CREATED', 'PUBLISHED', 'CLOSED', name='tenderstatus'),
            nullable=False,
        ),
        sa.Column(
            'service_type',
            sa.Enum(
                'CONSTRUCTION', 'DELIVERY', 'MANUFACTURE', name='servicetype'
            ),
            nullable=False,
        ),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organization.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['employee.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'bids',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'CREATED',
                'PUBLISHED',
                'CANCELLED',
                'APPROVED',
                'REJECTED',
                name='bidstatus',
            ),
            nullable=False,
        ),
        sa.Column('author_type', sa.String(length=255), nullable=False),
        sa.Column('author_id', sa.UUID(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('tender_id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'], ['employee.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organization.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tender_id'],
            ['tenders.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'BidsHistory',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('bid_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'CREATED',
                'PUBLISHED',
                'CANCELLED',
                'APPROVED',
                'REJECTED',
                name='bidstatus',
            ),
            nullable=False,
        ),
        sa.Column('author_type', sa.String(length=255), nullable=False),
        sa.Column('author_id', sa.UUID(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('tender_id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'], ['employee.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['bid_id'],
            ['bids.id'],
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organization.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tender_id'],
            ['tenders.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BidsHistory')
    op.drop_table('bids')
    op.drop_table('tenders')
    op.drop_table('tender_history')
    # op.drop_table('organization_responsible')
    # op.drop_table('organization')
    # op.drop_table('employee')
    # ### end Alembic commands ###
